import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://fcrkmsjhceswscumxqlz.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjcmttc2poY2Vzd3NjdW14cWx6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY0NzczOTM3NSwiZXhwIjoxOTYzMzE1Mzc1fQ.lpuJsLpCEIfdoymiInXICrxknqYxJPFOKIpQhZxFJqo')